config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pics, :comments
  root 'pics#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pic

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  belongs_to :user
  has_many :comment

  has_attached_file :image, styles: { large: '400x400>', medium: "300x300>", thumb: "100x100>" }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pic

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new(pic_id: params[:pic_id])
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to root_path, notice: 'Comment Added'
    else
      render 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :pic_id)
  end

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [:show, :edit, :update, :destroy, :find_comments]


  def index
    @pics = Pic.all.order('created_at DESC')
  end

  def show
    @comments = find_comments
  end

  def new
    @pic = current_user.pic.build
  end

  def create
    @pic = current_user.pic.build(pic_params)

    if @pic.save
      redirect_to @pic, notice: "Picture Added"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: 'Updated Pic info'
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end

  private

  def pic_params
    params.require(:pic).permit(:title, :description, :image)
  end

  def find_pic
    @pic = Pic.find(params[:id])
  end

  def find_comments
    @comments = Comment.where(['pic_id =:p',{ p: @pic.id}])
  end


#   dont repeat ourseleves

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/comments/_form.html.haml
= simple_form_for @comment, html: { multipart: true } do |f|
  - if @comment.errors.any?
    #errors
      %h2
      = pluralize(@comment.errors.count, 'error')
      prevented this comment from saving
      %ul
        - @comment.errors.full_message.each  do |msg|
          %li = msg

  .form-group
    = f.input :content, input_html: { class: 'form-control' }
    = f.hidden_field :pic_id, value: params[:pic_id]


  = f.button :submit, clsas: 'btn btn-info'

app/views/comments/new.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Add Comments
      .panel-body
        = render 'form'

        = link_to 'back', root_path

app/views/comments/show.html.haml
-#= image_tag @pic.image.url(:large)
-#%h1= 'Title: ' + @pic.title
-#%p= 'Description: ' + @pic.description
-#%p= 'Picture uploader: ' + @pic.user.email
-#=
-#
-#=link_to 'Add Comment', new_comment_path(pic_id: @pic.id),:controller => 'comments'
-#=link_to 'Back', root_path
-#=link_to 'Edit', edit_pic_path
-#=link_to 'Delete', pic_path, method: :delete, data: { confirm: 'Are you sure?'}

app/views/layouts/application.haml
%html
%head
  <title>App for cookpad</title>
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
</head>
%body

  %nav.navbar.navbar-inverse
    .container
      .navbar-brand= link_to 'Image App', root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-left
          %li= link_to 'Add Pic', new_pic_path
          %li= link_to 'Settings', edit_user_registration_path
          %li= link_to 'Sign Out', destroy_user_session_path, method: :delete

      - else
        %ul.nav.navbar-nav.navbar-left
          %li= link_to 'Sign Up', new_user_registration_path
          %li= link_to 'Login', new_user_session_path



  .container
    -flash.each do |name, msg|
      =content_tag :div, msg, class: 'alert alert-info'

    = yield

</body>
</html>

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true } do |f|
  - if @pic.errors.any?
    #errors
      %h2
      = pluralize(@pic.errors.count, 'error')
      prevented this pic from saving
      %ul
        - @pic.errors.full_message.each  do |msg|
          %li = msg

  .form-group
    = f.input :image, input_html: { class: 'form-control' }
  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit, clsas: 'btn btn-info'

app/views/pics/edit.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Picture
      .panel-body
        .current_image
          %strong.center Current Picture
          = image_tag @pic.image.url(:medium)
        = render 'form'

        = link_to 'back', root_path

app/views/pics/index.html.haml
- @pics.each do |pic|
  = link_to (image_tag pic.image.url(:large)), pic
  %h2= link_to pic.title, pic

= link_to 'Add new pic', new_pic_path

app/views/pics/new.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Add Pictures
      .panel-body
        = render 'form'

        = link_to 'back', root_path

app/views/pics/show.html.haml
= image_tag @pic.image.url(:large)
%h1= 'Title: ' + @pic.title
%h3= 'Description: ' + @pic.description
%h3= 'Picture uploader: ' + @pic.user.email

- @comments.each do |comment|
  %h6= 'Comment: ' + comment.content


=link_to 'Add Comment', new_comment_path(:pic_id => @pic.id),:controller => 'comments'
=link_to 'Back', root_path
=link_to 'Edit', edit_pic_path
=link_to 'Delete', pic_path, method: :delete, data: { confirm: 'Are you sure?'}